# Generated by Django 4.2 on 2024-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0002_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashed_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
