# Generated by Django 4.2 on 2024-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0003_post_hashed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashed_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
