# Generated by Django 4.2 on 2024-07-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0006_post_share_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='share_password',
        ),
    ]
