# Generated by Django 4.2 on 2024-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0007_remove_post_share_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
