# Generated by Django 5.0.7 on 2024-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0009_vaultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
