# Generated by Django 5.0.7 on 2024-07-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0010_vaultfile_original_name_vaultfile_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultfile',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='vaultfile',
            name='size',
        ),
    ]
