# Generated by Django 5.0.7 on 2024-07-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0011_remove_vaultfile_original_name_remove_vaultfile_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaultFile',
        ),
    ]
