# Generated by Django 5.0.7 on 2024-08-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0013_hiddenfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenfile',
            name='created_at',
        ),
    ]
